- name: Deploy Web Server
  hosts: localhost
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start nginx
      service:
        name: nginx
        state: started

    - name: Create index file
      copy:
        content: "<h1>Hello from DevOps Project 🚀</h1>"
        dest: /var/www/html/index.html
